import { readFile } from "node:fs/promises";

const html = await readFile(new URL("../index.html", import.meta.url), "utf8");

const required = [
  'id="screenshot-course"',
  'href="#screenshot-course"',
  "完整实操课：从打开 Codex 到交付结果",
  "步骤 01",
  "步骤 12",
  'id="china-access"',
  'href="#china-access"',
  "Codex 国内站使用教程",
  '<details class="nav-group" open>',
  '<summary>01 新手入门</summary>',
  '<summary>02 Codex 国内站</summary>',
  '<summary>03 Codex 指令保姆级教程</summary>',
  '<summary>04 Codex 项目实战</summary>',
  'href="#project-browser-control"',
  'href="#project-inquiry-site"',
  'href="#project-solo-wechat-mini"',
  'href="#project-personal-site"',
  'href="#project-product-video"',
  'href="#project-ppt"',
  'id="project-browser-control"',
  'id="project-inquiry-site"',
  'id="project-solo-wechat-mini"',
  'id="project-personal-site"',
  'id="project-product-video"',
  'id="project-ppt"',
  "操控浏览器",
  "询盘外贸独立站",
  "一人公司微信小程序",
  "个人网站",
  "产品宣传视频",
  "PPT",
  "Codex 项目实战训练营",
  "6 个可展示项目",
  "直播带练",
  "交付物",
  "席位",
  '<summary>Agent 超级应用 Codex，七大核心能力拆解</summary>',
  'href="#ultimate-codex-project"',
  'href="#ultimate-local-files"',
  'href="#ultimate-memory-skills"',
  'href="#ultimate-plugins-automation"',
  '<summary>06 一句话安装 Hermes Agent，微信全能秘书</summary>',
  'href="#hermes-agent-secretary"',
  'href="#hermes-agent-install"',
  'href="#hermes-agent-wechat"',
  'id="ultimate-codex-project"',
  'id="ultimate-local-files"',
  'id="ultimate-memory-skills"',
  'id="ultimate-plugins-automation"',
  'id="hermes-agent-secretary"',
  'id="hermes-agent-install"',
  'id="hermes-agent-wechat"',
  "Codex 终极实战",
  "Agent 超级应用",
  "ChatGPT 用来聊，Codex 干活",
  "Claude Code",
  "完整的文件访问权限",
  "60 张收据",
  "53 张收据",
  "Excel 工作簿",
  "Project 管理文件",
  "agents.md",
  "memories",
  "插件生态",
  "Gmail 插件",
  "Notion 插件",
  "Skill 系统",
  "brand deal researcher",
  "GPT Image",
  "产品照片",
  "浏览器控制和电脑控制",
  "Canva 演示文稿",
  "@browser use",
  "自动化",
  "每周五上午 9 点",
  "Chronicle",
  "隐私边界",
  "一句话安装 Hermes Agent，微信全能秘书",
  "一句话安装Hermes Agent，从此享有全能秘书",
  "刘小排",
  "OpenClaw",
  "通用Agent",
  "自我进化",
  "海外的网络环境",
  "ChatGPT Plus/Pro",
  "完全访问权限",
  "GPT-5.5 xhigh",
  "Clawdbot",
  "扫码绑定",
  "重要的微信消息",
  "主力电脑",
  '<summary>07 模板与资料</summary>',
  'href="#china-start"',
  'href="#china-config"',
  'href="#china-first-task"',
  'href="#china-faq"',
  'id="china-start"',
  'id="china-config"',
  'id="china-first-task"',
  'id="china-faq"',
  'id="slash-commands"',
  'href="#slash-commands"',
  "Codex 指令保姆级教程",
  "普通 prompt = 让 Codex 干什么活",
  "/init",
  "/resume",
  "https://x.com/dengdry/status/2052026438442725525",
  'id="slash-overview"',
  'id="slash-command-set"',
  'id="slash-sidefork"',
  'id="slash-workflow"',
  'id="slash-practice"',
  'href="#slash-overview"',
  'href="#slash-command-set"',
  'href="#slash-sidefork"',
  'href="#slash-workflow"',
  'href="#slash-practice"',
  "本节大纲",
];

const missing = required.filter((text) => !html.includes(text));

const ids = [...html.matchAll(/\sid="([^"]+)"/g)].map((match) => match[1]);
const hrefs = [...html.matchAll(/href="#([^"]+)"/g)].map((match) => match[1]);
const brokenAnchors = hrefs.filter((href) => href !== "top" && !ids.includes(href));
const duplicateIds = ids.filter((id, index) => ids.indexOf(id) !== index);
const navGroupCount = [...html.matchAll(/<details class="nav-group"/g)].length;
const forbiddenLayout = [
  "right-toc",
  "progress-card",
  "toc-list",
  "product-courses",
  "product-board",
  "product-item",
  "全部产品",
].filter((text) => html.includes(text));
const publicScreenshotWording = [
  "截图",
  "截图里",
  "截图里的",
  "你补充的截图",
  "从截图提取",
  "复盘材料",
  "微信公众号文章入口",
  "https://mp.weixin.qq.com/s/Cp1f7KpEzZ-PqOI62dNF0Q",
  "https://mp.weixin.qq.com/s/a6FCHSkZnimbpL2albBsaw",
].filter((text) => html.includes(text));

if (missing.length || brokenAnchors.length || duplicateIds.length || navGroupCount !== 7 || forbiddenLayout.length || publicScreenshotWording.length) {
  console.error("index.html validation failed");
  if (missing.length) console.error("Missing content:", missing.join(", "));
  if (brokenAnchors.length) console.error("Broken anchors:", brokenAnchors.join(", "));
  if (duplicateIds.length) console.error("Duplicate section ids:", duplicateIds.join(", "));
  if (navGroupCount !== 7) console.error("Expected 7 nav groups, found:", navGroupCount);
  if (forbiddenLayout.length) console.error("Forbidden right-side layout:", forbiddenLayout.join(", "));
  if (publicScreenshotWording.length) console.error("Forbidden screenshot-source wording:", publicScreenshotWording.join(", "));
  process.exit(1);
}

console.log(`index.html validation passed: ${ids.length} sections, ${hrefs.length} anchors`);
